### ISSUE TITLE
StreamInterface vs resource.

### ISSUE THREAD

**Issue by andris-sevcenko** [Superbalist/flysystem-google-cloud-storage#53] opened 2017-02-10 10:37 UTC
In the tests, the stream is being [explicitly tested being an instance of StreamInterface](https://github.com/andris-sevcenko/flysystem-google-cloud-storage/blob/master/tests/GoogleStorageAdapterTests.php#L550).

This stream is returned back further in [Filesystem::readStream()](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L199).

The problem here, however, is that the Filesystem interface states that the method [should be returning a resource](https://github.com/thephpleague/flysystem/blob/master/src/FilesystemInterface.php#L36).

It's not a problem for me to check if I'm getting a StreamInterface or a resource, but this is probably a little bit misleading. I also realise that this is a backwards-compatibility breaking change, so that raises the stakes a bit. Or, maybe I'm wrong. In that case do not hesitate to call me a fool.

**Comment by matthewgoslett** [comment] 2017-02-10 14:16
Thanks, we definitely should be returning a resource and not the StreamInterface, which we bubble down from the the Google Cloud lib - https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Storage/StorageObject.php#L608

Whilst we've deviated from the interface, I'm not sure I'd like to consider it a breaking change.  In the unit test, we incorrectly test for a StreamInterface, but in the actual class, we inheritdoc and say we return a resource (even though we don't).

I'm open to thoughts on this.

I'll patch it when I have a sec.
It looks like we should be calling `\GuzzleHttp\Stream\GuzzleStreamWrapper:: getResource(...)` to convert the StreamInterface to a PHP resource.

**Comment by andris-sevcenko** [comment] 2017-02-10 14:26
Well, if somebody is using that method and relying that to return StreamInterface, they might consider this a breaking change, if it's changed to resource :)

**Comment by andris-sevcenko** [comment] 2017-02-21 12:13
Any progress on this one?

**Comment by matthewgoslett** [comment] 2017-02-22 06:42
I've merged this into master now.
Will push this into a 5.0.0 release.

**Comment by tmirks** [comment] 2017-03-30 21:17
This breaks [`MountManager::copy()`](https://github.com/thephpleague/flysystem/blob/master/src/MountManager.php#L205-L213) which passes the buffer up to [`Filesystem::writeStream()`](https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L76) and subsequently throws an exception.

I can confirm that the latest commit fixes this issue.

**Comment by andris-sevcenko** [comment] 2017-03-31 05:44
Yup. Hoping for a 5.0 release soon.

**Comment by matthewgoslett** [comment] 2017-04-03 13:24
I've pushed a new major, 5.0.0 with the above fix.

https://github.com/Superbalist/flysystem-google-cloud-storage/releases/tag/5.0.0

Thanks!

**Closed** 2017-04-03 13:24 UTC
Labels: bug
